{{/*
This template is only used when externalSecrets.enabled is true.
For normal deployments, secrets are managed by the deployment script.

The deployment script creates secrets via:
kubectl create secret generic <release-name>-secrets --from-literal=...

This template provides a fallback for external secret management systems.
*/}}
{{- if .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalSecrets.secretName }}
  labels:
    {{- include "oauth2proxy.labels" . | nindent 4 }}
  annotations:
    # This secret is managed by external secrets operator
    # or other external secret management system
type: Opaque
data:
  # These will be populated by your external secret management system
  {{ .Values.externalSecrets.keys.clientId }}: ""
  {{ .Values.externalSecrets.keys.clientSecret }}: ""
  {{ .Values.externalSecrets.keys.cookieSecret }}: ""
{{- else }}
{{/*
When externalSecrets.enabled is false (default), secrets are managed by:
1. The deployment script: ./kagent-oauth2proxy.sh (recommended)
2. Environment variables: OAUTH2_PROXY_CLIENT_ID, etc.
3. Direct kubectl commands

The deployment script automatically creates a secret named:
{{ include "oauth2proxy.fullname" . }}-secrets

No secret template is needed in this case.
*/}}
{{- end }} 
